app:
  name: api-api
  environment: local
  debug: on
server:
  port: 19999
database:
  host: localhost
  port: 5432
  username: your-username
  password: your-password
  extra:
    max_connections: 100
    timeout: 30