CREATE TABLE `api_doc`.`collection` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR ( 255 ) NOT NULL COMMENT '名称',
    `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户id',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY ( `id` )
);